/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PatelDev (https://sketchfab.com/PatelDev)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-Earths/earth-f7a76c63ff1846afb2d606e5c8369c15
title: Earth
*/

import React ,{useRef}from 'react'
import { useGLTF } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'

 function Earth(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  const meshRef = useRef()
  useFrame(()=>{
    // we can mutate // animate // the mesh so we need ref
    meshRef.current.rotation.y += 0.01
    // meshRef.current.position.z += 0.01
    // meshRef.current.rotation.z += 0.01
    // meshRef.current.rotation.x += 0.01
    //execute on every frame 

})

  return (
    <group  scale={20} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={5}>
            <mesh ref={meshRef} geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']}
             position={props.props.earth_position}/>
          </group>
        </group>
      </group>
    </group>
  )
}
export default Earth
useGLTF.preload('/earth.gltf')
