/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: PounUP (https://sketchfab.com/PounUP)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/planet-0104234961624b7aa0cb85d03161babe
title: Planet
*/

// import React, { useRef } from 'react'
// import { useSpring } from '@react-spring/three'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import Yoda from './Yoda'
import Plane from './Plane'


 function PounUP (props) {
  const { nodes, materials } = useGLTF('/PounUP.gltf')
  const meshRef =useRef()
  
  useFrame(()=>{
    // we can mutate // animate // the mesh so we need ref
    meshRef.current.rotation.y += 0.01
    // meshRef.current.position.z += 0.01
    // meshRef.current.rotation.z += 0.01
    // meshRef.current.rotation.x += 0.001
    //execute on every frame 

})
useFrame(()=>{
  // we can mutate // animate // the mesh so we need ref
  // anotherRef.current.rotation.y += 0.01
  // anotherRef.current.rotation.z += 0.01
  // anotherRef.current.rotation.x += 0.01

  //execute on every frame 

})
  return (
    <group>    
          <Yoda position={[0,1,0]}/>
          <Plane size={[100,100]}/>
    
    <group {...props} dispose={null}  ref={meshRef}>
      <group >
        <group  >
          <group position={[0, 0,0]} rotation={[-Math.PI / 2, 0, 0]} scale={150} >
            <mesh geometry={nodes.COMBINE_LP_LAM_0.geometry} material={materials.material} />
            <mesh geometry={nodes.COMBINE_LP_1_0.geometry} material={materials.material_1} />
            <mesh geometry={nodes.COMBINE_LP_2_0.geometry} material={materials.material_2} />
          </group>
        </group>
      </group>
    </group>
    </group>
  )
}

export default PounUP
useGLTF.preload('/PounUP.gltf')
