/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Renan Arruda (https://sketchfab.com/renanalvesarruda)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mestre-yoda-maionerdmctech-9b9fe302981d41da9bfd1ef89e2856db
title: Mestre Yoda #MaioNerdMcTech
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export  default function Yoda(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/yoda.gltf')
  const { actions,names } = useAnimations(animations, group)
  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.1).play()

  },[names,actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.1} position={props.position}>
          <group name="9170815b871f4652afe5ced3111e36cafbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object001" position={[-13.73, 21.79, 6.19]} rotation={[0.45, -0.06, 0.05]} scale={2.23} />
                <group name="Dummy001" position={[0, 17.19, -6.77]} scale={0.76}>
                  <group name="Object_5">
                    {/* {console.log(names)} */}
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_116" rotation={[-Math.PI / 2, 0, 0]} />
                    <group name="Object_118" position={[-13.71, 41.7, 12.04]} rotation={[0.44, 0, 0.01]} scale={2.23} />
                    <skinnedMesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.corpo_MAT} skeleton={nodes.Object_117.skeleton} />
                    <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.Sabre_Luz_MAT} skeleton={nodes.Object_119.skeleton} />
                  </group>
                </group>
                <group name="2" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="bengala_MOD" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="bengala_MOD_bengala_MAT_0" geometry={nodes.bengala_MOD_bengala_MAT_0.geometry} material={materials.bengala_MAT} />
                </group>
                <group name="capa_MOD" rotation={[-Math.PI / 2, 0, 0]}>
                  <mesh name="capa_MOD_capa_MAT_0" geometry={nodes.capa_MOD_capa_MAT_0.geometry} material={materials.capa_MAT} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/yoda.gltf')
