import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next JS pre-rendering</h1>
      <Link href='/users'> Users</Link>
      <Link href='/posts'> Post</Link>

      {/*  Any <Link/> component in the viewport(initially or through scroll) will be prefetched by default (including the corresponding data ) for pages using static Generation */}
      {/* with other word if you have link to  another page fetch will be done at initial rendering (pre fetching)*/}
    </>
  )
}


 

